postgresql:
  auth:
    existingSecret: app-stack-postgresql-external
    secretKeys:
      adminPasswordKey: password
      userPasswordKey: password
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      registry: docker.io
      repository: bitnamilegacy/os-shell