frontend:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

backend:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

postgresql:
  primary:
    persistence:
      enabled: false
  auth:
    username: appuser
    database: appdb
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      registry: docker.io
      repository: bitnamilegacy/os-shell