apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-stack-postgresql-external
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-mock-store
    kind: SecretStore
  target:
    name: app-stack-postgresql-external
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: db-credentials
        property: password