apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-mock-store
  namespace: default
spec:
  provider:
    kubernetes:
      remoteNamespace: vault-mock
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-store-reader